-- Seed content_blocks from i18n data (part 1 of 4)
INSERT INTO public.content_blocks (page, section, key, type, locale, value) VALUES
('nav', 'general', 'home', 'text', 'en', 'Home'),
('nav', 'general', 'recipes', 'text', 'en', 'Recipes'),
('nav', 'general', 'plan', 'text', 'en', 'Plan'),
('nav', 'general', 'progress', 'text', 'en', 'Progress'),
('nav', 'general', 'profile', 'text', 'en', 'Profile'),
('nav', 'general', 'signIn', 'text', 'en', 'Sign In'),
('home', 'general', 'healthIsWealth', 'text', 'en', 'Health is'),
('home', 'general', 'healthIsWealth2', 'text', 'en', 'Wealth.'),
('home', 'general', 'healingJourney', 'text', 'en', 'Your healing journey'),
('home', 'general', 'recommendedForYou', 'text', 'en', 'Recommended for you'),
('home', 'general', 'updatePreferences', 'text', 'en', 'Update your preferences'),
('home', 'general', 'resetTitle', 'text', 'en', 'Reset your preferences?'),
('home', 'general', 'resetDesc', 'text', 'en', 'This will restart the onboarding quiz. Your personalized content will update based on your new answers.'),
('home', 'general', 'cancel', 'text', 'en', 'Cancel'),
('home', 'general', 'resetRedo', 'text', 'en', 'Reset & Redo'),
('home', 'general', 'motivationTitle', 'text', 'en', 'Need extra motivation?'),
('home', 'general', 'motivationDesc', 'text', 'en', 'Talk to seasoned carnivores — book a coaching call.'),
('home', 'features', 'benefits', 'text', 'en', 'Benefits'),
('home', 'features', 'recipes', 'text', 'en', 'Recipes'),
('home', 'features', 'ketosisTimer', 'text', 'en', 'Ketosis Timer'),
('home', 'features', 'ingredients', 'text', 'en', 'Ingredients'),
('home', 'features', 'exercise', 'text', 'en', 'Exercise'),
('home', 'features', 'cravings', 'text', 'en', 'Cravings'),
('home', 'features', 'sustainResults', 'text', 'en', 'Sustain Results'),
('home', 'features', 'mythsBusted', 'text', 'en', 'Myths Busted'),
('home', 'features', 'completeGuide', 'text', 'en', 'Complete Guide'),
('home', 'features', 'first30Days', 'text', 'en', 'First 30 Days'),
('home', 'features', 'eatOnBudget', 'text', 'en', 'Eat on a Budget'),
('home', 'features', 'athleticFuel', 'text', 'en', 'Athletic Fuel'),
('home', 'greetings', 'lose_weight', 'text', 'en', 'Let''s burn fat today'),
('home', 'greetings', 'build_muscle', 'text', 'en', 'Time to build strength'),
('home', 'greetings', 'maintain', 'text', 'en', 'Stay consistent, stay strong'),
('home', 'greetings', 'improve_health', 'text', 'en', 'Your healing journey continues'),
('home', 'subtitles', 'lose_weight', 'text', 'en', 'High-protein, zero-carb fuel for maximum fat loss.'),
('home', 'subtitles', 'build_muscle', 'text', 'en', 'Fuel your gains with nature''s most anabolic diet.'),
('home', 'subtitles', 'maintain', 'text', 'en', 'Steady nutrition for sustained performance.'),
('home', 'subtitles', 'improve_health', 'text', 'en', 'Let food be your medicine — meat heals.'),
('home', 'tips', 'sugar_cravings', 'text', 'en', 'Craving sweets? Try bone broth or fatty cuts — they crush sugar cravings fast.'),
('home', 'tips', 'low_energy', 'text', 'en', 'Low energy? Make sure you''re eating enough fat — it''s your new fuel source.'),
('home', 'tips', 'digestive', 'text', 'en', 'Digestive adjustment is normal. Stick with fattier cuts and give your gut time.'),
('home', 'tips', 'social_pressure', 'text', 'en', 'Facing pushback? Check out Success Stories from people who''ve been there.'),
('nav', 'general', 'home', 'text', 'fr', 'Accueil'),
('nav', 'general', 'recipes', 'text', 'fr', 'Recettes'),
('nav', 'general', 'plan', 'text', 'fr', 'Planifier'),
('nav', 'general', 'progress', 'text', 'fr', 'Progrès'),
('nav', 'general', 'profile', 'text', 'fr', 'Profil'),
('nav', 'general', 'signIn', 'text', 'fr', 'Connexion'),
('home', 'general', 'healthIsWealth', 'text', 'fr', 'La santé,'),
('home', 'general', 'healthIsWealth2', 'text', 'fr', 'c''est la richesse.'),
('home', 'general', 'healingJourney', 'text', 'fr', 'Votre parcours de guérison'),
('home', 'general', 'recommendedForYou', 'text', 'fr', 'Recommandé pour vous'),
('home', 'general', 'updatePreferences', 'text', 'fr', 'Modifier vos préférences'),
('home', 'general', 'resetTitle', 'text', 'fr', 'Réinitialiser vos préférences ?'),
('home', 'general', 'resetDesc', 'text', 'fr', 'Cela relancera le quiz d''intégration. Votre contenu personnalisé sera mis à jour en fonction de vos nouvelles réponses.'),
('home', 'general', 'cancel', 'text', 'fr', 'Annuler'),
('home', 'general', 'resetRedo', 'text', 'fr', 'Réinitialiser'),
('home', 'general', 'motivationTitle', 'text', 'fr', 'Besoin de motivation ?'),
('home', 'general', 'motivationDesc', 'text', 'fr', 'Échangez avec des carnivores expérimentés — réservez un appel coaching.'),
('home', 'features', 'benefits', 'text', 'fr', 'Bienfaits'),
('home', 'features', 'recipes', 'text', 'fr', 'Recettes'),
('home', 'features', 'ketosisTimer', 'text', 'fr', 'Chrono cétose'),
('home', 'features', 'ingredients', 'text', 'fr', 'Ingrédients'),
('home', 'features', 'exercise', 'text', 'fr', 'Exercices'),
('home', 'features', 'cravings', 'text', 'fr', 'Envies'),
('home', 'features', 'sustainResults', 'text', 'fr', 'Maintenir ses résultats'),
('home', 'features', 'mythsBusted', 'text', 'fr', 'Mythes démystifiés'),
('home', 'features', 'completeGuide', 'text', 'fr', 'Guide complet'),
('home', 'features', 'first30Days', 'text', 'fr', 'Les 30 premiers jours'),
('home', 'features', 'eatOnBudget', 'text', 'fr', 'Manger petit budget'),
('home', 'features', 'athleticFuel', 'text', 'fr', 'Performance sportive'),
('home', 'greetings', 'lose_weight', 'text', 'fr', 'Brûlons du gras aujourd''hui'),
('home', 'greetings', 'build_muscle', 'text', 'fr', 'C''est l''heure de se renforcer'),
('home', 'greetings', 'maintain', 'text', 'fr', 'Restez constant, restez fort'),
('home', 'greetings', 'improve_health', 'text', 'fr', 'Votre parcours de guérison continue'),
('home', 'subtitles', 'lose_weight', 'text', 'fr', 'Alimentation hyperprotéinée, zéro glucide pour une perte de gras maximale.'),
('home', 'subtitles', 'build_muscle', 'text', 'fr', 'Alimentez vos gains avec le régime le plus anabolisant de la nature.'),
('home', 'subtitles', 'maintain', 'text', 'fr', 'Nutrition stable pour une performance soutenue.'),
('home', 'subtitles', 'improve_health', 'text', 'fr', 'Que la nourriture soit votre remède — la viande guérit.'),
('home', 'tips', 'sugar_cravings', 'text', 'fr', 'Envie de sucre ? Essayez le bouillon d''os ou les morceaux gras — ils éliminent les envies de sucre rapidement.'),
('home', 'tips', 'low_energy', 'text', 'fr', 'Peu d''énergie ? Assurez-vous de manger suffisamment de gras — c''est votre nouvelle source d''énergie.'),
('home', 'tips', 'digestive', 'text', 'fr', 'L''adaptation digestive est normale. Privilégiez les morceaux gras et laissez du temps à votre système digestif.'),
('home', 'tips', 'social_pressure', 'text', 'fr', 'Vous subissez des pressions ? Consultez les témoignages de personnes qui sont passées par là.')
ON CONFLICT (page, section, key, locale) DO UPDATE SET value = EXCLUDED.value, updated_at = now();