INSERT INTO public.content_blocks (page, section, key, locale, type, value) VALUES
('onboarding','health_targets','subtitle','en','text','Select everything that applies — we''ll personalize your plan around it'),
('onboarding','health_targets','cat_metabolic','en','text','Metabolic health'),
('onboarding','health_targets','cat_inflammation','en','text','Inflammation'),
('onboarding','health_targets','cat_gut','en','text','Gut health'),
('onboarding','health_targets','cat_mental','en','text','Mind & mood'),
('onboarding','health_targets','cat_energy','en','text','Energy & performance'),
('onboarding','health_targets','cat_hormonal','en','text','Hormonal health'),
('onboarding','health_targets','blood_pressure','en','text','Blood pressure'),
('onboarding','health_targets','insulin_sensitivity','en','text','Insulin sensitivity'),
('onboarding','health_targets','chronic_inflammation','en','text','Chronic inflammation'),
('onboarding','health_targets','joint_pain','en','text','Joint pain'),
('onboarding','health_targets','autoimmune','en','text','Autoimmune symptoms'),
('onboarding','health_targets','skin_issues','en','text','Skin issues'),
('onboarding','health_targets','bloating','en','text','Bloating'),
('onboarding','health_targets','food_sensitivities','en','text','Food sensitivities'),
('onboarding','health_targets','mental_clarity','en','text','Mental clarity'),
('onboarding','health_targets','brain_fog','en','text','Brain fog'),
('onboarding','health_targets','mood','en','text','Mood stability'),
('onboarding','health_targets','sleep','en','text','Sleep quality'),
('onboarding','health_targets','sustained_energy','en','text','Sustained energy'),
('onboarding','health_targets','athletic_performance','en','text','Athletic performance'),
('onboarding','health_targets','recovery','en','text','Recovery'),
('onboarding','health_targets','muscle_mass','en','text','Muscle mass'),
('onboarding','health_targets','hormone_balance','en','text','Hormone balance'),
('onboarding','health_targets','thyroid','en','text','Thyroid function'),
('onboarding','health_targets','testosterone','en','text','Testosterone'),
('onboarding','health_targets','fertility','en','text','Fertility'),
('onboarding','health_targets','subtitle','fr','text','Sélectionnez tout ce qui s''applique — nous personnaliserons votre plan'),
('onboarding','health_targets','cat_metabolic','fr','text','Santé métabolique'),
('onboarding','health_targets','cat_inflammation','fr','text','Inflammation'),
('onboarding','health_targets','cat_gut','fr','text','Santé intestinale'),
('onboarding','health_targets','cat_mental','fr','text','Esprit & humeur'),
('onboarding','health_targets','cat_energy','fr','text','Énergie & performance'),
('onboarding','health_targets','cat_hormonal','fr','text','Santé hormonale'),
('onboarding','health_targets','blood_pressure','fr','text','Tension artérielle'),
('onboarding','health_targets','insulin_sensitivity','fr','text','Sensibilité à l''insuline'),
('onboarding','health_targets','chronic_inflammation','fr','text','Inflammation chronique'),
('onboarding','health_targets','joint_pain','fr','text','Douleurs articulaires'),
('onboarding','health_targets','autoimmune','fr','text','Symptômes auto-immuns'),
('onboarding','health_targets','skin_issues','fr','text','Problèmes de peau'),
('onboarding','health_targets','bloating','fr','text','Ballonnements'),
('onboarding','health_targets','food_sensitivities','fr','text','Sensibilités alimentaires'),
('onboarding','health_targets','mental_clarity','fr','text','Clarté mentale'),
('onboarding','health_targets','brain_fog','fr','text','Brouillard mental'),
('onboarding','health_targets','mood','fr','text','Stabilité de l''humeur'),
('onboarding','health_targets','sleep','fr','text','Qualité du sommeil'),
('onboarding','health_targets','sustained_energy','fr','text','Énergie durable'),
('onboarding','health_targets','athletic_performance','fr','text','Performance sportive'),
('onboarding','health_targets','recovery','fr','text','Récupération'),
('onboarding','health_targets','muscle_mass','fr','text','Masse musculaire'),
('onboarding','health_targets','hormone_balance','fr','text','Équilibre hormonal'),
('onboarding','health_targets','thyroid','fr','text','Fonction thyroïdienne'),
('onboarding','health_targets','testosterone','fr','text','Testostérone'),
('onboarding','health_targets','fertility','fr','text','Fertilité')
ON CONFLICT (page, section, key, locale) DO NOTHING;